using System;
using System.Collections.Generic;
using System.Text;

namespace subbuzz.Parser
{
    public static class SubtitleFileExtensions
    {
        private static readonly List<string> _fileExtensions = new List<string>()
        {
            ".aqt",
            ".asc",
            ".ass",
            ".ats",
            ".aya",
            ".cac",
            ".cap",
            ".caption",
            ".chk",
            ".cin",
            ".crk",
            ".csv",
            ".ctm",
            ".detx",
            ".dfxp",
            ".dtc",
            ".dv",
            ".edl",
            ".elr",
            ".eztxml",
            ".fcpxml",
            ".fdx",
            ".flc",
            ".fte",
            ".gst",
            ".html",
            ".idx",
            ".imtpro",
            ".inqscr",
            ".itt",
            ".json",
            ".jss",
            ".lrc",
            ".m2ts",
            ".mcc",
            ".mvt",
            ".pac",
            ".pjs",
            ".pns",
            ".psl",
            ".pst",
            ".rt",
            ".rtf",
            ".sbv",
            ".scc",
            ".sif",
            ".smi",
            ".son",
            ".spt",
            ".sptx",
            ".srt",
            ".ssa",
            ".STL",
            ".stp",
            ".sub",
            ".subtitle",
            ".ted",
            ".tek",
            ".titl",
            ".tmm",
            ".tmx",
            ".trs",
            ".ttml",
            ".tts",
            ".ttxt",
            ".tx3g",
            ".txt",
            ".ult",
            ".usf",
            ".utx",
            ".vid",
            ".vtt",
            ".WSB",
            ".xif",
            ".xml",
            ".xmp",
            ".xsubtitle",
            ".zeg",
        };

        public static HashSet<string> Extensions => new HashSet<string>(_fileExtensions, StringComparer.OrdinalIgnoreCase);
    }
}
